- name: Create NFS mountpoint
  become: yes
  file:
    path: /data
    state: directory

- name: Mount NFS volume
  become: yes
  ansible.posix.mount:
    src: "{{ server_host }}:/data"
    path: /data
    opts: "{{ nfs_mount_opts }}"
    state: mounted
    fstype: nfs
